name: Deploy

on:
  push:
    branches: ['main']

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '>=20.6.0'
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm run build

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
      run: |
        gh release create "$tag" \
          --repo="$GITHUB_REPOSITORY" \
          --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
          -F CHANGELOG.md
        

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: game-of-life
        path: ./dist/
  
