name: Deploy

on:
  push:
    branches: ['main']

jobs:
  publish-package:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '>=20.6.0'
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: | 
        pnpm run build
        zip game-of-life.zip ./dist/*

    - name: Get project version from package.json
      run: echo "project_version=$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"

    - name: Create release
      run: gh release create $project_version ./dist/*.zip -F CHANGELOG.md

    # - name: Upload build to release
    #   run: gh release upload $project_version ./dist/
      
  
