name: Deploy

on:
  push:
    branches: ['main']

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 8
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
    - uses: actions/setup-node@v4
      with:
        node-version: '>=20.6.0'
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install
    - name: Build and Publish
      run: |
        pnpm run build
        pnpm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
