name: Deploy

on:
  push:
    branches: ['main']

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '>=20.6.0'
    - uses: pnpm/action-setup@v4
      with:
        version: 8
    
    - name: Build
      run: |
        pnpm install
        pnpm version patch
        pnpm run build
        pnpm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
